name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: school_db
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup JDK for Spring Boot
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Adjust to match your project's JDK version

      # Step 3: Build and Test Backend
      - name: Build and Test Backend
        run: |
          cd School-Management-System-Spring-Boot
          mvn clean install
          mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/school_db
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root

      # Step 4: Setup Node.js for Angular
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      # Step 5: Install and Build Frontend
      - name: Install and Build Frontend
        run: |
          cd School-Management-System-Angular
          npm install
          npm run build

      # Step 6: Upload Test and Build Artifacts (Optional)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            School-Management-System-Spring-Boot/target
            School-Management-System-Angular/dist
